### ISSUE TITLE
Why is colour applied only after picker tool is closed?

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/circle-colourer#1]
The colour is applied to the circle but only after the colour picker is closed. Any tips what I might be doing wrong?

Also, not sure why but Markbot is expecting to see a different value for width, height and border-radius inside `.ball { }`.

Thanks @thomasjbradley

**Comment by thomasjbradley** [comment]
> The colour is applied to the circle but only after the colour picker is closed. Any tips what I might be doing wrong?

I think that’s just the way it works. The browser doesn’t fire the `change` event until that point.

**Comment by thomasjbradley** [comment]
Ball width/height should be `100px`. With a border-radius of `50px`.
